### ISSUE TITLE
Access Handlers from Interceptor

### ISSUE THREAD

**Issue by anandmukundan** [stoiveyp/Alexa.NET.RequestHandlers#8]
Hi @stoiveyp Is it possible to get access to the selected handler from the interceptor?

E.g.

Interceptor1

Handler1
Handler2

When Interceptor is called, I assume the correct handler is already selected as the delegate to call Handle is passed to the Intercept method. Is it possible to get access to and instance of the selected handler?

I have a scenario where the interceptor needs to query the handler to get some information and then work on that information. I don't want to store that information in the interceptor as that would break the abstraction.

Thanks

**Comment by anandmukundan** [comment]
Just as soon as I posted I found the commit on HandlerAwareInterceptor :)

Will take a look at that.

**Comment by stoiveyp** [comment]
Hi @anandmukundan - sounds like the HandlerAware interface will do what you need. It was added as an inherited interface purely to ensure that I didn't break previous interceptors unnecessarily.

Feel free to re-open this issue if you find it's not fit for purpose.
